### ISSUE TITLE
Issue on Stop Tailing

### ISSUE THREAD

**Issue by marioffmarques** [hpcloud/tail#47]
Hello,

I'm using this func 
err := t.Stop()

to stop tailing activity on a file, however this not stops the tailing. Is this the correct aproach to stop tailing ? If not, how can I achieve my goal ?
Thanks in advance

**Comment by Nino-K** [comment]
@marioffmarques Can you paste a bit of your code so we can see how t.Stop() is being called?
Generally you want to read lines while you are subscribed to the Lines chan and have some sort of stop chan that stops the tailing process. e.g.

```
stopCh := make(chan bool)

for {
		select {
		case line, ok := <-t.Lines:
			if !ok {
				err = t.Wait()
				break 
			}
			// do something with the line 
		case <-stopCh:
			err = t.Stop()
			break 
		}
	}
```

**Comment by marioffmarques** [comment]
Firstly, thanks for the reply. For reading lines, I have this block of code:


	  	tailHandle, err := tail.TailFile(filePath, tail.Config{Follow: true})
		for line := range tailHandle.Lines {
		    fmt.Println("Readed: " + line.Text)
		}

And for stop the tailing I use this: 
                tailHandle.Stop()

**Comment by sparrc** [comment]
@marioffmarques this indicates an issue in your code handling goroutines, this is not an issue with the tail package

**Comment by Nino-K** [comment]
@marioffmarques going to close this issue, as it seems not related to tail.
