### ISSUE TITLE
Put logging behind Interface

### ISSUE THREAD

**Issue by pquerna** [hpcloud/tail#52]
Currently the `Config.Logger` is of type `*log.Logger`, which is a Logger struct: 

http://golang.org/pkg/log/#Logger

This makes using alternative logging implementations, eg https://github.com/Sirupsen/logrus fairly difficult, because it is a bare structure reference, and not an Interface -- so the only real option is to pass an io.Writer into `log.New`, and then proxy that data to Logrus.

Ideally `tail` could make an interface of the functions it actually wants for logging, and making a proxy type to logrus would be easy.

**Comment by srid** [comment]
+1, PR welcome.

Since this will be an API change it will have to go with [v1](https://github.com/ActiveState/tail/issues/51#issuecomment-115238728).
