### ISSUE TITLE
OS X Inotify watcher not working

### ISSUE THREAD

**Issue by binary132** [hpcloud/tail#70]
Using OS X El Capitan.  `Tail.Lines` is open, but nothing ever comes out.  I've poked around with various options to see if I can get it working, but nothing ever works unless I use `Poll: true` in the `Config` passed to `TailFile`.  I'll try and open a PR with a failing test sometime in the next week or two.

**Comment by sparrc** [comment]
I'm using OSX El Capitan and haven't had any issues. @binary132 can you reproduce it in a small snippet of code?
