### ISSUE TITLE
Unix sockets support

### ISSUE THREAD

**Issue by panda87** [hpcloud/tail#86]
I want to suggest another path, which is unix sockets.
For example, we are using many docker containers on one host, and I'd like to be able to get the logs on real time from the docker.sock.

Thanks
D.

**Comment by Nino-K** [comment]
@panda87  I believe getting logs in real time over unix socket is beyond the scope of what tail should be responsible for, having said that you should be able to tail your log files on your container(s) using this library depending on how/what file system you are using for your containers. If you are still considering to stream your logs over some sort of socket or using docker stream api, you should still be able to do this with a small utility.
