### ISSUE TITLE
No buildable

### ISSUE THREAD

**Issue by iandriyanov** [hpcloud/tail#91]
# go get github.com/hpcloud/tail/...

../../hpcloud/tail/watch/inotify.go:13:2: no buildable Go source files in /opt/local/go16/manual/src/github.com/hpcloud/tail/vendor/gopkg.in/fsnotify.v1

**Comment by Nino-K** [comment]
@iandriyanov I tested the issue you pointed out on `OSX`, `ubuntu` and can not reproduce it. Can you check your `GOPATH` is set correctly.

I'm going to close this issue.
